# Generated by Django 3.2.9 on 2021-11-03 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasMate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=7)),
                ('dificultad', models.CharField(max_length=20)),
                ('contenido', models.CharField(max_length=200)),
                ('pregunta', models.TextField()),
                ('solucion', models.TextField()),
                ('pista', models.CharField(max_length=200)),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.TextField()),
                ('alternative', models.TextField()),
                ('solution', models.CharField(max_length=1)),
                ('times_tried', models.IntegerField()),
                ('times_result', models.IntegerField()),
                ('points', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_questions', models.IntegerField(default=0)),
                ('punctuation', models.IntegerField(default=0)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
