# Generated by Django 3.2.8 on 2021-11-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='preguntaPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pregunta', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=200)),
                ('pregunta_math', models.TextField(max_length=200)),
                ('alternativa_a', models.TextField(max_length=50)),
                ('alternativa_b', models.TextField(max_length=50)),
                ('alternativa_c', models.TextField(max_length=50)),
                ('alternativa_d', models.TextField(max_length=50)),
                ('solucion_math', models.TextField(max_length=50)),
            ],
        ),
    ]
