# Generated by Django 3.2.8 on 2021-11-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20211107_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasmate',
            name='alternativa_correcta',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_e',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
