# Generated by Django 3.2.9 on 2021-11-09 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApp', '0005_auto_20211107_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasmate',
            name='siglas',
            field=models.CharField(choices=[('MAT021', 'Mat-021'), ('MAT022', 'Mat-022'), ('MAT023', 'Mat-023'), ('MAT024', 'Mat-024')], max_length=7),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='tema',
            field=models.CharField(choices=[('numeros_reales', 'Números Reales'), ('funciones', 'Funciones'), ('limite', 'Límites'), ('continuidad', 'Continuidad'), ('calculo_diferencial', 'Cálculo Diferencial'), ('logica_proposicional', 'Lógica Proposicional'), ('conjunto', 'Conjuntos'), ('relaciones', 'Relaciones'), ('trigonometria', 'Trigonometría'), ('exponencial_logaritmo', 'Exponencial y Logaritmo'), ('geometria_analitica', 'Geometría Analítica'), ('induccion', 'Inducción'), ('sumatoria_productoria', 'Sumatoria y Productoria'), ('numeros_complejos', 'Números Complejos'), ('polinomios', 'Polinomios')], max_length=100),
        ),
        migrations.CreateModel(
            name='PostForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('MAT021', 'Mat-021'), ('MAT022', 'Mat-022'), ('MAT023', 'Mat-023'), ('MAT024', 'Mat-024')], max_length=7)),
                ('texto', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
