# Generated by Django 3.2.9 on 2021-11-09 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('WebApp', '0006_auto_20211109_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_correcta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='dificultad',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIA', 'Media'), ('DIFICIL', 'Difícil')], max_length=20),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('object_id', models.PositiveIntegerField()),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tiempo'],
            },
        ),
    ]
