# Generated by Django 3.2.8 on 2021-11-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_auto_20211112_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcertamen',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
