# Generated by Django 3.2.8 on 2021-11-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_alter_historialcertamen_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcertamen',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
