# Generated by Django 3.2.8 on 2021-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_alter_historialcertamen_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcertamen',
            name='id_certamen',
            field=models.CharField(default='', max_length=20),
        ),
    ]
