# Generated by Django 3.2.8 on 2021-11-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_historialcertamen_id_certamen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['punctuation']},
        ),
    ]
