# Generated by Django 3.2.9 on 2021-11-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postforo',
            options={'ordering': ['-tiempo']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.comentario'),
        ),
    ]
