# Generated by Django 3.2.9 on 2021-11-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_auto_20211120_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.comentario'),
        ),
    ]
