# Generated by Django 3.2.9 on 2021-11-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_alter_comentario_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.comentario'),
        ),
    ]
