# Generated by Django 3.2.8 on 2021-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_auto_20211121_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcertamen',
            name='n_correctas',
            field=models.CharField(default='', max_length=20),
        ),
    ]
