# Generated by Django 3.2.8 on 2021-11-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_alter_historialcertamen_n_correctas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcertamen',
            name='alternativa_marcadas',
            field=models.CharField(default='', max_length=100),
        ),
    ]
