# Generated by Django 3.2.8 on 2021-11-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_historialcertamen_alternativa_marcadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_a',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_b',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_c',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_d',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasmate',
            name='alternativa_e',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
