# Generated by Django 3.2.8 on 2021-11-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_auto_20211130_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='preguntaPrueba',
        ),
    ]
