# Generated by Django 3.2.8 on 2021-12-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_delete_preguntaprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.comentario'),
        ),
    ]
