# Generated by Django 3.2.9 on 2021-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0024_alter_comentario_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=2500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='postforo',
            name='texto',
            field=models.TextField(max_length=2500),
        ),
    ]
