# Generated by Django 3.2.9 on 2021-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0025_auto_20211209_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforo',
            name='slug',
            field=models.SlugField(blank=True, max_length=2500, unique=True),
        ),
    ]
