# Generated by Django 3.2.8 on 2021-12-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_alter_historialcertamen_id_preguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcertamen',
            name='hora_termino',
            field=models.CharField(default='', max_length=11),
        ),
    ]
