# Generated by Django 3.2.8 on 2021-12-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0029_profile_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='elo',
            field=models.CharField(default='Mechon', max_length=30),
        ),
    ]
